/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package fu.swt301.sms.service;

import fu.swt301.sms.dao.StaffDAO;
import fu.swt301.sms.entity.Role;
import fu.swt301.sms.entity.Staff;
import fu.swt301.sms.utils.DBUtils;
import fu.swt301.sms.utils.PasswordUtils;
import org.junit.jupiter.api.*;

import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.math.BigDecimal;
import java.time.LocalDate;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.doNothing;
import static org.mockito.Mockito.spy;

@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class LockOutIntegrationTest {
private static Connection h2Connection;
    private StaffDAO staffDAO;
    private AuthService authService;

    private final String TEST_EMAIL = "test-lock@example.com";
    private final String CORRECT_PASSWORD = "password123";
    private final String WRONG_PASSWORD = "wrong-password";

    @BeforeAll
    public static void setupH2Database() throws Exception {
        // 🔥 Sửa đổi: Thêm thuộc tính CASE_INSENSITIVE_IDENTIFIERS=TRUE vào URL
        String h2Url = "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MSSQLServer;CASE_INSENSITIVE_IDENTIFIERS=TRUE";
        Connection realH2Conn = DriverManager.getConnection(h2Url, "sa", "");

        // Sử dụng Mockito Spy để chặn hàm close() như bước trước
        h2Connection = spy(realH2Conn);
        doNothing().when(h2Connection).close();

        String initSql = 
            "CREATE TABLE IF NOT EXISTS Role (" +
            "  Role_ID INT PRIMARY KEY, " +
            "  Role_Name VARCHAR(50) NOT NULL" +
            "); " +
            "CREATE TABLE IF NOT EXISTS Staff (" +
            "  StaffID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
            "  StaffCode VARCHAR(20), " +
            "  FullName VARCHAR(100), " +
            "  DateOfBirth DATE, " +
            "  Gender BOOLEAN, " +
            "  PhoneNumber VARCHAR(20), " +
            "  Email VARCHAR(100) UNIQUE, " +
            "  Password VARCHAR(255), " +
            "  Department VARCHAR(100), " +
            "  Position VARCHAR(100), " +
            "  Salary DECIMAL(18,2), " +
            "  HireDate DATE, " +
            "  Role_ID INT, " +
            "  IsActive BOOLEAN, " +
            "  FOREIGN KEY (Role_ID) REFERENCES Role(Role_ID)" +
            ");";

        try (Statement stmt = realH2Conn.createStatement()) {
            stmt.execute(initSql);
            stmt.execute("INSERT INTO Role (Role_ID, Role_Name) VALUES (1, 'Admin'), (2, 'Staff');");
        }

        DBUtils.setTestConnection(h2Connection);
    }
    
    @AfterAll
    public static void tearDownH2() throws Exception {
        if (h2Connection != null && !h2Connection.isClosed()) {
            h2Connection.close();
        }
    }

    @BeforeEach
    public void setUp() throws Exception {
        staffDAO = new StaffDAO();
        authService = new AuthService(); 

        // Làm sạch bảng Staff trước mỗi test case
        try (Statement stmt = h2Connection.createStatement()) {
            stmt.execute("TRUNCATE TABLE Staff"); 
        }

        // Chèn 1 tài khoản test có sẵn trạng thái IsActive = true
        String seedSql = "INSERT INTO Staff (StaffCode, FullName, DateOfBirth, Gender, PhoneNumber, Email, "
                + "Password, Department, Position, Salary, HireDate, Role_ID, IsActive) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        try (PreparedStatement ps = h2Connection.prepareStatement(seedSql)) {
            ps.setString(1, "STF999");
            ps.setString(2, "Hieu Nguyen");
            ps.setObject(3, java.sql.Date.valueOf(LocalDate.of(2002, 5, 20)));
            ps.setBoolean(4, true);
            ps.setString(5, "0912345678");
            ps.setString(6, TEST_EMAIL);
            ps.setString(7, PasswordUtils.hashPassword(CORRECT_PASSWORD)); // Pass đã mã hóa
            ps.setString(8, "IT");
            ps.setString(9, "Developer");
            ps.setBigDecimal(10, new BigDecimal("20000000"));
            ps.setObject(11, java.sql.Date.valueOf(LocalDate.now()));
            ps.setInt(12, 1); // Admin
            ps.setBoolean(13, true); 
            ps.executeUpdate();
        }
    }

    @Test
    @Order(1)
    @DisplayName("IT_LOCK_001: Đăng nhập thành công từ DB ảo H2 tạo bằng URL-Init")
    public void testLogin_Success() {
        LoginResult result = authService.login(TEST_EMAIL, CORRECT_PASSWORD);
        assertTrue(result.isSuccess());
        assertEquals("Hieu Nguyen", result.getStaff().getFullName());
    }

    @Test
    @Order(2)
    @DisplayName("IT_LOCK_002: Khóa tài khoản sau 5 lần nhập sai và cập nhật IsActive dưới H2")
    public void testAccountLockout_UpdatesDatabase() {
        LoginResult result = null;

        // Hành động: Đăng nhập sai liên tiếp 5 lần
        for (int i = 0; i < 5; i++) {
            result = authService.login(TEST_EMAIL, WRONG_PASSWORD);
        }

        // 1. Check thông báo lỗi lần thứ 5
        assertTrue(result.getErrorMessage().contains("Attempt 5/5") || result.getErrorMessage().contains("locked"));

        // 2. Check biến lưu trên RAM Map
        assertTrue(authService.isAccountLocked(TEST_EMAIL));

        // 3. ĐIỂM CHỐT: Check xem DB H2 ảo đã bị cập nhật về IsActive = false chưa
       Staff staffInH2 = staffDAO.getStaffByEmail(TEST_EMAIL); 

        assertNotNull(staffInH2, "Phải tìm thấy tài khoản test trong DB ảo");
        assertFalse(staffInH2.isIsActive(), "Trường IsActive trong DB ảo phải tự động chuyển thành FALSE!");
    }
    
}
